execute pathogen#infect()

syntax on
let g:solarized_termcolors=256
set t_Co=256
set background=dark
colorscheme solarized

set tabstop=2
set softtabstop=0
set expandtab
set shiftwidth=2
set smarttab
